/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import static java.awt.PageAttributes.MediaType.D;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author thebu
 */
public class Ana_Giris extends javax.swing.JFrame {

    /**
     * Creates new form Ana_Giris
     */
    public Ana_Giris() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        lbl_giris_yazisi = new javax.swing.JLabel();
        btn_ogrenci_giris = new javax.swing.JButton();
        btn_yonetici_giris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl.setBackground(new java.awt.Color(0, 153, 204));

        lbl_giris_yazisi.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbl_giris_yazisi.setText("Fatih Sultan Mehmet Vakıf Üniversitesine Hoşgeldiniz");

        btn_ogrenci_giris.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_ogrenci_giris.setText("ÖĞRENCİ GİRİŞİ");
        btn_ogrenci_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogrenci_girisActionPerformed(evt);
            }
        });

        btn_yonetici_giris.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_yonetici_giris.setText("YÖNETİCİ GİRİŞİ");
        btn_yonetici_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yonetici_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_giris_yazisi))
                    .addGroup(pnlLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_ogrenci_giris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_yonetici_giris, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbl_giris_yazisi)
                .addGap(61, 61, 61)
                .addComponent(btn_ogrenci_giris)
                .addGap(41, 41, 41)
                .addComponent(btn_yonetici_giris)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ogrenci_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogrenci_girisActionPerformed
        //Sadece frame geçişi yaptım
        Ogrenci_Giris_Ekrani ögrenci_giris = new Ogrenci_Giris_Ekrani();
        ögrenci_giris.setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_btn_ogrenci_girisActionPerformed

    private void btn_yonetici_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yonetici_girisActionPerformed
        
        //Sadece frame geçişi yaptım
        Yönetici_giris_ekranı yg = new Yönetici_giris_ekranı();
        yg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_yonetici_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ana_Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ana_Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ana_Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ana_Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ana_Giris().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ogrenci_giris;
    private javax.swing.JButton btn_yonetici_giris;
    private javax.swing.JLabel lbl_giris_yazisi;
    private javax.swing.JPanel pnl;
    // End of variables declaration//GEN-END:variables
}
