/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thebu
 */
public class Ogrenci_Giris_Ekrani extends javax.swing.JFrame {

    /**
     * Creates new form Login_Ekrani
     */
    public Ogrenci_Giris_Ekrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_student_id = new javax.swing.JLabel();
        lbl_ogrenci_parola = new javax.swing.JLabel();
        txt_student_mail = new javax.swing.JTextField();
        psw_student_psw = new javax.swing.JPasswordField();
        btn_giris_yap = new javax.swing.JButton();
        btn_kayit_ol = new javax.swing.JButton();
        btn_vazgec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        lbl_student_id.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_student_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_student_id.setText("Öğrenci Mail : ");

        lbl_ogrenci_parola.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_ogrenci_parola.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ogrenci_parola.setText("Öğrenci Parolası : ");

        btn_giris_yap.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_giris_yap.setText("GİRİŞ YAP");
        btn_giris_yap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giris_yapActionPerformed(evt);
            }
        });

        btn_kayit_ol.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_kayit_ol.setText("KAYIT OL");
        btn_kayit_ol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayit_olActionPerformed(evt);
            }
        });

        btn_vazgec.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_vazgec.setText("VAZGEÇ");
        btn_vazgec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vazgecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_student_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_ogrenci_parola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_student_mail)
                            .addComponent(psw_student_psw, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addContainerGap(119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_vazgec, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_kayit_ol, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_student_id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_student_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ogrenci_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psw_student_psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kayit_ol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_giris_yap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_vazgec, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayit_olActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayit_olActionPerformed
        // TODO add your handling code here:

        Öğrenci_kayit_ekrani ögrenci_kayit = new Öğrenci_kayit_ekrani();
        ögrenci_kayit.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_kayit_olActionPerformed

    private void btn_giris_yapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giris_yapActionPerformed
        // TODO add your handling code here:

        
        Pattern pattern = Pattern.compile("^([a-z]+\\w*){1,}@{1}(stu){1}(.fsm){1}(.edu){1}(.tr){1}$");
        Matcher matcher = pattern.matcher(this.txt_student_mail.getText());

        String kullaniciAD = this.txt_student_mail.getText();
        String sifre = this.psw_student_psw.getText();

        if (this.txt_student_mail.getText().isEmpty() || this.psw_student_psw.getText().isEmpty()) {//bosluk kontrolü

            JOptionPane.showMessageDialog(rootPane, "Lutfen Tüm Bosluklari Doldurunuz", "Dikkat", JOptionPane.ERROR_MESSAGE);

        } else {

            if (!matcher.find()) {// burada reggex kontrolü yaptım
                JOptionPane.showMessageDialog(rootPane, "Giriş Yapmak İçin example@stu.fsm.edu.tr olarak giriş yapmalısınız", "Dikkat", JOptionPane.INFORMATION_MESSAGE);
            } else {

                Kullanici giris_yapan_kullanici = db_student_and_manager.login_islemi(kullaniciAD, sifre);

                if (giris_yapan_kullanici != null) {// kullanıcı boş mu kontrolü

                    if (giris_yapan_kullanici.kullanıcı_tip.compareTo("Öğrenci") == 0) {//öğrenci tipine bakılır

                        JOptionPane.showMessageDialog(rootPane, "Basariyla Giris Yapilmistir", "Merhabalar", JOptionPane.INFORMATION_MESSAGE);
                        Ogrenci_ekrani o = new Ogrenci_ekrani(giris_yapan_kullanici);
                        o.setlbl_öğrenci(giris_yapan_kullanici.ad_soyad);
                        o.setVisible(true);
                        this.dispose();
                        //öğrenci  başarıyla giriş yapıp yeni ekrana geçer

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Yöneticiler Lütfen Yönetici Giriş Sayfasindan Giris Yapiniz", "Dikkat!!", JOptionPane.INFORMATION_MESSAGE);
                        Ana_Giris a = new Ana_Giris();
                        a.setVisible(true);
                        this.dispose();
                        //yönetici girş yapmaya kalkarsa ana girişe atar

                    }

                } else {
                    //sistem de böyle bir kullanıcı yoksa bu mesaj gelir
                    JOptionPane.showMessageDialog(rootPane, "Böyle Bir Öğrenci Bulunamamaktadir!!", "Dikkat", JOptionPane.ERROR_MESSAGE);
                    this.txt_student_mail.setText("");
                    this.psw_student_psw.setText("");

                }

            }

        }


    }//GEN-LAST:event_btn_giris_yapActionPerformed

    private void btn_vazgecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vazgecActionPerformed
        // TODO add your handling code here:
        Ana_Giris a = new Ana_Giris();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_vazgecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ogrenci_Giris_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ogrenci_Giris_Ekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris_yap;
    private javax.swing.JButton btn_kayit_ol;
    private javax.swing.JButton btn_vazgec;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_ogrenci_parola;
    private javax.swing.JLabel lbl_student_id;
    private javax.swing.JPasswordField psw_student_psw;
    private javax.swing.JTextField txt_student_mail;
    // End of variables declaration//GEN-END:variables
}
