/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thebu
 */
public class ogrenci_ders_program extends javax.swing.JFrame {

    /**
     * Creates new form ögrenci_ders_program
     */
    DefaultTableModel tbl_ders_program_model;
    Kullanici ögrenci;

    public ogrenci_ders_program(Kullanici ögrenci) {
        initComponents();
        this.ögrenci = ögrenci;
        tbl_ders_program_model = new DefaultTableModel();
        tbl_ders_program_model.setColumnIdentifiers(new Object[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
        tbl_ders_program.setModel(tbl_ders_program_model);
        set_table();
    }

    public ogrenci_ders_program() {
        initComponents();
        tbl_ders_program_model = new DefaultTableModel();
        tbl_ders_program_model.setColumnIdentifiers(new Object[]{"Ders Saati", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma"});
        tbl_ders_program.setModel(tbl_ders_program_model);
        set_table();
    }

    public void set_table() {
        ArrayList<kurslar> kurslar = db_student_and_manager.Ogrencinin_secili_derslerini_getir(this.ögrenci.id);
        //bu kısımda fonksiyondan gelen kursları yeni bir array de tutar o arraya göre en son da ders programı tablosuna ekler
        String[] k = new String[5];
        for (kurslar kurs : kurslar) {

            if (kurs.name.equals("Matematik")) {
                k[0] = "Matematik";

            } else if (kurs.name.equals("Fizik")) {
                k[1] = "Fizik";
            } else if (kurs.name.equals("Mühendislik Dersi")) {
                k[2] = "Mühendislik Dersi";

            } else if (kurs.name.equals("Kimya")) {
                k[3] = "Kimya";
            } else if (kurs.name.equals("Lineer Cebir")) {
                k[4] = "Lineer Cebir";

            } else {
                k[0] = "";
                k[1] = "";
                k[2] = "";
                k[3] = "";
                k[4] = "";

            }

        }

        tbl_ders_program_model.addRow(new Object[]{"Ders Saati: 09.00 ", k[0], "", "", k[0]});
        tbl_ders_program_model.addRow(new Object[]{"Ders Saati: 10.15 ", "", k[1], "", "", k[1]});
        tbl_ders_program_model.addRow(new Object[]{"Ders Saati: 11.30 ", k[2], "", "", k[2]});
        tbl_ders_program_model.addRow(new Object[]{"Ders Saati: 13.15 ", "", k[3], k[3], "", ""});
        tbl_ders_program_model.addRow(new Object[]{"Ders Saati: 13.15 ", "", "", k[4], "", k[4]});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ders_program = new javax.swing.JTable();
        btn_geri_don = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jScrollPane1.setViewportView(tbl_ders_program);

        btn_geri_don.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_geri_don.setText("Geri Dön");
        btn_geri_don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geri_donActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_geri_don)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_geri_don, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_geri_donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geri_donActionPerformed
        // TODO add your handling code here:
        Ogrenci_ekrani o = new Ogrenci_ekrani(ögrenci);
        o.setlbl_öğrenci(ögrenci.ad_soyad);
        o.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_geri_donActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrenci_ders_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrenci_ders_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrenci_ders_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrenci_ders_program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogrenci_ders_program().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri_don;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ders_program;
    // End of variables declaration//GEN-END:variables
}
