/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thebu
 */
public class Yöneticiden_Öğrenci_güncelleme extends javax.swing.JFrame {

    /**
     * Creates new form Yöneticiden_Öğrenci_güncelleme
     */
    Kullanici yönetici;
    DefaultTableModel tableModel1;
    DefaultTableModel tbl_kurslar_model;
    //modeller oluşturulur
    public Yöneticiden_Öğrenci_güncelleme(Kullanici yönetici) {
        initComponents();
        this.yönetici = yönetici;
        tableModel1 = new DefaultTableModel();
        tableModel1.setColumnIdentifiers(new Object[]{"Öğrenci ID", "Öğrenci İsmi"});
        tbl_ögrenciler.setModel(tableModel1);

        tbl_kurslar_model = new DefaultTableModel();
        tbl_ögrencinin_kurslari.setModel(tbl_kurslar_model);
        tbl_kurslar_model.setColumnIdentifiers(new Object[]{"Dersin ID si", "Dersin İsmi", "Derstten Alınan Not"});
        //table lar düzenlenir
    }

    public Yöneticiden_Öğrenci_güncelleme() {
        initComponents();
        tableModel1 = new DefaultTableModel();
        tableModel1.setColumnIdentifiers(new Object[]{"Öğrenci ID", "Öğrenci İsmi"});
        tbl_ögrenciler.setModel(tableModel1);

        tbl_kurslar_model = new DefaultTableModel();
        tbl_ögrencinin_kurslari.setModel(tbl_kurslar_model);
        tbl_kurslar_model.setColumnIdentifiers(new Object[]{"Dersin ID si", "Dersin İsmi", "Derstten Alınan Not"});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ögrenciler = new javax.swing.JTable();
        txt_search = new javax.swing.JTextField();
        btn_arama = new javax.swing.JButton();
        lbl_ogrenci_id = new javax.swing.JLabel();
        lbl_ogrenci_ad_soyad = new javax.swing.JLabel();
        lbl_ogrenci_mail = new javax.swing.JLabel();
        lbl_ogrenci_bolum = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_ad_soyad = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_bölüm = new javax.swing.JTextField();
        lbl_ogrenci_bolum_sec = new javax.swing.JLabel();
        combobx_bölüm = new javax.swing.JComboBox<>();
        btn_ögrenci_güncelle = new javax.swing.JButton();
        lbl_ogrenci_parola = new javax.swing.JLabel();
        psw_parola = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_ögrencinin_kurslari = new javax.swing.JTable();
        lbl_oğrencinin_Aldigi_dersler = new javax.swing.JLabel();
        btn_geridön = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        tbl_ögrenciler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ögrencilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ögrenciler);

        btn_arama.setText("Öğrenci Ara");
        btn_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aramaActionPerformed(evt);
            }
        });

        lbl_ogrenci_id.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_id.setText("Öğrenci ID:");

        lbl_ogrenci_ad_soyad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_ad_soyad.setText("Öğrenci Ad Soyadı :");

        lbl_ogrenci_mail.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_mail.setText("Öğrenci Maili :");

        lbl_ogrenci_bolum.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_bolum.setText("Öğrencinin Bölümü : ");

        txt_id.setEditable(false);

        txt_bölüm.setEditable(false);

        lbl_ogrenci_bolum_sec.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_bolum_sec.setText("Öğrenci Bölümü Değişikliği : ");

        combobx_bölüm.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        combobx_bölüm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilgisayar Mühendisliği", "İnşaat Mühendisliği", "Endüstri Mühendisliği", "Yazılım Mühendisliği", "Optik Mühendisliği", "Elektrik Mühendisliği" }));
        combobx_bölüm.setSelectedIndex(-1);
        combobx_bölüm.setToolTipText("");
        combobx_bölüm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobx_bölümMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combobx_bölümMousePressed(evt);
            }
        });

        btn_ögrenci_güncelle.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_ögrenci_güncelle.setText("Öğrenci Bilgilerini Güncelle");
        btn_ögrenci_güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ögrenci_güncelleActionPerformed(evt);
            }
        });

        lbl_ogrenci_parola.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_parola.setText("Öğrencinin Parolası :");

        psw_parola.setEditable(false);

        tbl_ögrencinin_kurslari.setEnabled(false);
        jScrollPane2.setViewportView(tbl_ögrencinin_kurslari);

        lbl_oğrencinin_Aldigi_dersler.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_oğrencinin_Aldigi_dersler.setText("Öğrencinin Aldığı Dersler Ve Notlar");

        btn_geridön.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_geridön.setText("Geri Dön");
        btn_geridön.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geridönActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_arama)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_geridön, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ögrenci_güncelle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ogrenci_bolum_sec)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_ogrenci_mail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ogrenci_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_ogrenci_ad_soyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_ogrenci_parola)
                            .addComponent(lbl_ogrenci_bolum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ad_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psw_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobx_bölüm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_oğrencinin_Aldigi_dersler, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_arama))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_oğrencinin_Aldigi_dersler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lbl_ogrenci_id))
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ogrenci_ad_soyad)
                            .addComponent(txt_ad_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ogrenci_mail))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(psw_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ogrenci_parola))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ogrenci_bolum)
                            .addComponent(txt_bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ogrenci_bolum_sec)
                            .addComponent(combobx_bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ögrenci_güncelle)
                            .addComponent(btn_geridön))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aramaActionPerformed
        
        tableModel1.setRowCount(0);
        this.txt_ad_soyad.setText("");
        this.txt_bölüm.setText("");
        this.txt_id.setText("");
        this.txt_mail.setText("");
        this.psw_parola.setText("");
        this.combobx_bölüm.setSelectedIndex(-1);
        //ilk önce özellikler sıfılanır
        String arama = this.txt_search.getText();

        ArrayList<Kullanici> KullaniciListesi = db_student_and_manager.Kayitlardan_yazilana_göre_arama(arama);
        //sonra ise string içinde ne yazıyorsa ona göre kullanıcıların id ve isimleri gelir
        for (Kullanici k : KullaniciListesi) {

            tableModel1.addRow(new Object[]{k.id, k.ad_soyad});

        }


    }//GEN-LAST:event_btn_aramaActionPerformed

    private void tbl_ögrencilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ögrencilerMouseClicked
        // TODO add your handling code here:

        if (this.tbl_ögrenciler.getSelectedRow() < 0) {
            return;
        }

        int id = (int) tableModel1.getValueAt(tbl_ögrenciler.getSelectedRow(), 0);

        Kullanici k = db_student_and_manager.id_e_göre_arama(id);

        if (k != null) {
            //secilen kullanıcının bütün özelliklerini framede ki kısımlara doldurulur
            this.txt_id.setText(k.id + "");
            this.txt_ad_soyad.setText(k.ad_soyad);
            this.txt_mail.setText(k.mail);
            this.txt_bölüm.setText(k.bölüm);
            this.psw_parola.setText(k.parola);

            //kullanıcının bölümünü combo box ta işaretler
            if (k.bölüm.equals("Bilgisayar Mühendisliği")) {
                combobx_bölüm.setSelectedIndex(0);
            } else if (k.bölüm.equals("İnşaat Mühendisliği")) {
                combobx_bölüm.setSelectedIndex(1);
            } else if (k.bölüm.equals("Endüstri Mühendisliği")) {
                combobx_bölüm.setSelectedIndex(2);
            } else if (k.bölüm.equals("Yazılım Mühendisliği")) {
                combobx_bölüm.setSelectedIndex(3);
            } else if (k.bölüm.equals("Optik Mühendisliği")) {
                combobx_bölüm.setSelectedIndex(4);
            } else if (k.bölüm.equals("Elektrik Mühendisliği")) {
                combobx_bölüm.setSelectedIndex(5);
            }

            ArrayList<kurslar> kurslar = db_student_and_manager.Ogrencinin_secili_derslerini_getir(id);

            //bu kısımda da öğrencinin aldığı dersler ve notlar döndürülür
            tbl_kurslar_model.setRowCount(0);
            for (kurslar kurs : kurslar) {
                tbl_kurslar_model.addRow(new Object[]{kurs.id, kurs.name, kurs.alınan_not});
            }

        }


    }//GEN-LAST:event_tbl_ögrencilerMouseClicked

    private void btn_ögrenci_güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ögrenci_güncelleActionPerformed
        // TODO add your handling code here
        
        //maili @stu.fsm.edu.tr olarak girilmesini zorunlu tutan reggex kontrolü
        Pattern pattern = Pattern.compile("^([a-z]+\\w*){1,}@{1}(stu){1}(.fsm){1}(.edu){1}(.tr){1}$");
        Matcher matcher = pattern.matcher(this.txt_mail.getText());

        if (tbl_ögrenciler.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen Bir Öğrenci Seçiniz", "Dikkat", JOptionPane.ERROR_MESSAGE);
        } else {

            if (txt_id.getText().isEmpty() || txt_ad_soyad.getText().isEmpty() || txt_mail.getText().isEmpty() || psw_parola.getText().isEmpty() || txt_bölüm.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Lutfen Tüm Bosluklari Doldurunuz", "Dikkat", JOptionPane.ERROR_MESSAGE);
            } else {
                if (!matcher.find()) {//reggex kontrolü
                    JOptionPane.showMessageDialog(rootPane, "Öğrenciyi Güncellemek İçin Öğrencinin maili example@stu.fsm.edu.tr Şeklinde Olmalıdır", "Dikkat", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    //yeni kullanıcı olarak oluşturulup güncellenir
                    Kullanici k = new Kullanici();
                    k.ad_soyad = this.txt_ad_soyad.getText();
                    k.mail = txt_mail.getText();
                    k.parola = psw_parola.getText();
                    k.bölüm = combobx_bölüm.getSelectedItem().toString();
                    k.id = Integer.parseInt(txt_id.getText());
                    //txt te ki bilgiler tek tek alınır daha sonrasında ise veri tabanından aşağıdaki fonksiyona göre güncellenir
                    if (db_student_and_manager.kullanıcıGüncelle(k)) {
                        JOptionPane.showMessageDialog(rootPane, "Öğrenci Başarıyla Güncellenmiştir", "dikkat", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Öğrenci Güncellenememiştir", "dikkat", JOptionPane.INFORMATION_MESSAGE);

                    }
                }
            }

        }

    }//GEN-LAST:event_btn_ögrenci_güncelleActionPerformed

    private void combobx_bölümMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobx_bölümMouseClicked
        //

    }//GEN-LAST:event_combobx_bölümMouseClicked

    private void combobx_bölümMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobx_bölümMousePressed

    }//GEN-LAST:event_combobx_bölümMousePressed

    private void btn_geridönActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geridönActionPerformed
        // TODO add your handling code here:
        Yönetici_Ekrani y = new Yönetici_Ekrani(yönetici);
        y.setlbl_öğrenci(yönetici.ad_soyad);
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_geridönActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_Öğrenci_güncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_Öğrenci_güncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_Öğrenci_güncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_Öğrenci_güncelleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yöneticiden_Öğrenci_güncelleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arama;
    private javax.swing.JButton btn_geridön;
    private javax.swing.JButton btn_ögrenci_güncelle;
    private javax.swing.JComboBox<String> combobx_bölüm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ogrenci_ad_soyad;
    private javax.swing.JLabel lbl_ogrenci_bolum;
    private javax.swing.JLabel lbl_ogrenci_bolum_sec;
    private javax.swing.JLabel lbl_ogrenci_id;
    private javax.swing.JLabel lbl_ogrenci_mail;
    private javax.swing.JLabel lbl_ogrenci_parola;
    private javax.swing.JLabel lbl_oğrencinin_Aldigi_dersler;
    private javax.swing.JPasswordField psw_parola;
    private javax.swing.JTable tbl_ögrenciler;
    private javax.swing.JTable tbl_ögrencinin_kurslari;
    private javax.swing.JTextField txt_ad_soyad;
    private javax.swing.JTextField txt_bölüm;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
