/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thebu
 */
public class Yöneticiden_öğrenci_ekle extends javax.swing.JFrame {

    /**
     * Creates new form Yöneticiden_öğrenci_ekle
     */
    Kullanici yönetici;

    public Yöneticiden_öğrenci_ekle(Kullanici yönetici) {
        this.yönetici = yönetici;
        initComponents();
    }

    public Yöneticiden_öğrenci_ekle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_adsoyad = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_parola = new javax.swing.JLabel();
        lbl_bölüm = new javax.swing.JLabel();
        txt_adsoyad = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        psw_parola = new javax.swing.JPasswordField();
        combobx_bölüm = new javax.swing.JComboBox<>();
        btn_register = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lbl_adsoyad.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_adsoyad.setText("Öğrencinin Adı Soyadı : ");

        lbl_mail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_mail.setText("Öğrencinin Emaili : ");

        lbl_parola.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_parola.setText("Öğrencinin Parolası :");

        lbl_bölüm.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_bölüm.setText("Öğrencinin Bölümü : ");

        psw_parola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psw_parolaActionPerformed(evt);
            }
        });

        combobx_bölüm.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        combobx_bölüm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilgisayar Mühendisliği", "İnşaat Mühendisliği", "Endüstri Mühendisliği", "Yazılım Mühendisliği", "Optik Mühendisliği", "Elektrik Mühendisliği" }));
        combobx_bölüm.setToolTipText("");

        btn_register.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_register.setText("Kayıt Et");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_cancel.setText("Vazgeç");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_adsoyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_parola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_bölüm, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobx_bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psw_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_adsoyad)
                    .addComponent(txt_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbl_mail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psw_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_parola))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bölüm)
                    .addComponent(combobx_bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:

        Pattern pattern = Pattern.compile("^([a-z]+\\w*){1,}@{1}(stu){1}(.fsm){1}(.edu){1}(.tr){1}$");
        Matcher matcher = pattern.matcher(this.txt_mail.getText());

        if (this.txt_adsoyad.getText().isEmpty() || this.txt_mail.getText().isEmpty() || this.psw_parola.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Lutfen Tüm Bosluklari Doldurunuz", "Dikkat", JOptionPane.ERROR_MESSAGE);
        } else {

            if (!matcher.find()) {//regegxten sonra kullanıcı kayıt edilir
                JOptionPane.showMessageDialog(rootPane, "Öğrenci Eklemek İçin Öğrencinin Maili example@stu.fsm.edu.tr Şeklinde Olmalıdır", "Dikkat", JOptionPane.INFORMATION_MESSAGE);
            } else {

                Kullanici k = new Kullanici();
                k.ad_soyad = this.txt_adsoyad.getText();
                k.mail = this.txt_mail.getText();
                k.parola = this.psw_parola.getText();
                k.kullanıcı_tip = "Öğrenci";
                k.bölüm = combobx_bölüm.getSelectedItem().toString();

                if (db_student_and_manager.Add_kullanici(k)) {
                    JOptionPane.showMessageDialog(rootPane, "Öğrenci Basariyla Kayit Edildi", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
                    Yönetici_Ekrani y = new Yönetici_Ekrani(yönetici);
                    y.setlbl_öğrenci(yönetici.ad_soyad);
                    y.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Öğrenci Kayit Edilemedi", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
                    txt_adsoyad.setText("");
                    txt_mail.setText("");
                    psw_parola.setText("");
                    combobx_bölüm.setSelectedIndex(-1);
                }
            }
        }

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        Yönetici_Ekrani y = new Yönetici_Ekrani(yönetici);
        y.setlbl_öğrenci(yönetici.ad_soyad);
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void psw_parolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psw_parolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psw_parolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_öğrenci_ekle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_öğrenci_ekle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_öğrenci_ekle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yöneticiden_öğrenci_ekle.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yöneticiden_öğrenci_ekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_register;
    private javax.swing.JComboBox<String> combobx_bölüm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_adsoyad;
    private javax.swing.JLabel lbl_bölüm;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_parola;
    private javax.swing.JPasswordField psw_parola;
    private javax.swing.JTextField txt_adsoyad;
    private javax.swing.JTextField txt_mail;
    // End of variables declaration//GEN-END:variables
}
