/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thebu
 */
public class Yönetici_Kayit_Sayfasi extends javax.swing.JFrame {

    /**
     * Creates new form Yönetici_Kayit_Sayfasi
     */
    Kullanici yönetici;
    DefaultTableModel tableModel1;
    //modeller oluşturulur
    public Yönetici_Kayit_Sayfasi() {
        initComponents();
        tableModel1 = new DefaultTableModel();
        tableModel1.setColumnIdentifiers(new Object[]{"Öğrenci ID", "Öğrenci İsmi Ve Soyismi", "Öğrenci Mail", "Öğrenci Bölümü"});
        tbl_kayitli_olan_ögrenciler.setModel(tableModel1);
    }

    public Yönetici_Kayit_Sayfasi(Kullanici yönetici) {
        initComponents();
        this.yönetici = yönetici;
        tableModel1 = new DefaultTableModel();
        tableModel1.setColumnIdentifiers(new Object[]{"Öğrenci ID", "Öğrenci İsmi Ve Soyismi", "Öğrenci Mail", "Öğrenci Bölümü"});
        tbl_kayitli_olan_ögrenciler.setModel(tableModel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kayitli_olan_ögrenciler = new javax.swing.JTable();
        btn_kayıtlar = new javax.swing.JButton();
        btn_geri_dön = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jScrollPane1.setViewportView(tbl_kayitli_olan_ögrenciler);

        btn_kayıtlar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_kayıtlar.setText("Tüm Kayıtları Getir");
        btn_kayıtlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayıtlarActionPerformed(evt);
            }
        });

        btn_geri_dön.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_geri_dön.setText("Geri Dön");
        btn_geri_dön.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geri_dönActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_kayıtlar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_geri_dön, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_kayıtlar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_geri_dön, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kayıtlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayıtlarActionPerformed
        // TODO add your handling code here:

        tableModel1.setRowCount(0);
        ArrayList<Kullanici> KullaniciListesi = db_student_and_manager.tüm_ögrencileri_arama();

        for (Kullanici k : KullaniciListesi) {
            //bu kısımda yukarıdaki fonksiyon sayesinde tüm kullanıcılar gelir
            tableModel1.addRow(new Object[]{k.id, k.ad_soyad, k.mail, k.bölüm});

        }


    }//GEN-LAST:event_btn_kayıtlarActionPerformed

    private void btn_geri_dönActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geri_dönActionPerformed
        // TODO add your handling code here:
        
        Yönetici_Ekrani y = new Yönetici_Ekrani(yönetici);
        y.setVisible(true);
        y.setlbl_öğrenci(yönetici.ad_soyad);
        this.dispose();
        
    }//GEN-LAST:event_btn_geri_dönActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Kayit_Sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Kayit_Sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Kayit_Sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Kayit_Sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yönetici_Kayit_Sayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geri_dön;
    private javax.swing.JButton btn_kayıtlar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_kayitli_olan_ögrenciler;
    // End of variables declaration//GEN-END:variables
}
