/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import javax.swing.JOptionPane;

/**
 *
 * @author thebu
 */
public class Yönetici_Ekrani extends javax.swing.JFrame {
    //bu kısımda sadece frameler arası geçişler sağlanmaktadır

    Kullanici yönetici;

    /**
     * Creates new form Yönetici_Ekrani
     */
    public Yönetici_Ekrani() {
        initComponents();
    }

    public Yönetici_Ekrani(Kullanici yönetici) {
        initComponents();
        this.yönetici = yönetici;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_hosgeldiniz_mesaj = new javax.swing.JLabel();
        btn_öğrenci_ekle = new javax.swing.JButton();
        btn_ogrenci_güncelle = new javax.swing.JButton();
        btn_kayitlari_getir = new javax.swing.JButton();
        btn_guvenli_cikis = new javax.swing.JButton();
        btn_giris_ekrani = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_menu = new javax.swing.JMenu();
        menu_guvenli_cikis = new javax.swing.JMenuItem();
        menu_giris_ekranina_don = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        lbl_hosgeldiniz_mesaj.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        btn_öğrenci_ekle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_öğrenci_ekle.setText("Öğrenci Ekle");
        btn_öğrenci_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_öğrenci_ekleActionPerformed(evt);
            }
        });

        btn_ogrenci_güncelle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_ogrenci_güncelle.setText("Öğrenci Güncelle");
        btn_ogrenci_güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ogrenci_güncelleActionPerformed(evt);
            }
        });

        btn_kayitlari_getir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_kayitlari_getir.setText("Kayıtlar");
        btn_kayitlari_getir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitlari_getirActionPerformed(evt);
            }
        });

        btn_guvenli_cikis.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_guvenli_cikis.setText("Güvenli Çıkış Yap");
        btn_guvenli_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guvenli_cikisActionPerformed(evt);
            }
        });

        btn_giris_ekrani.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_giris_ekrani.setText("Giriş Ekranına Dön");
        btn_giris_ekrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_giris_ekraniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_hosgeldiniz_mesaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_öğrenci_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ogrenci_güncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addComponent(btn_kayitlari_getir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guvenli_cikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_giris_ekrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_hosgeldiniz_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_öğrenci_ekle)
                .addGap(18, 18, 18)
                .addComponent(btn_ogrenci_güncelle)
                .addGap(18, 18, 18)
                .addComponent(btn_kayitlari_getir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btn_giris_ekrani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guvenli_cikis)
                .addGap(19, 19, 19))
        );

        menu_menu.setText("Menü İşlemleri");

        menu_guvenli_cikis.setText("Güvenli Çıkış Yap");
        menu_guvenli_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_guvenli_cikisActionPerformed(evt);
            }
        });
        menu_menu.add(menu_guvenli_cikis);

        menu_giris_ekranina_don.setText("Giriş Ekranına Dön");
        menu_giris_ekranina_don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_giris_ekranina_donActionPerformed(evt);
            }
        });
        menu_menu.add(menu_giris_ekranina_don);

        jMenuBar1.add(menu_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_öğrenci_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_öğrenci_ekleActionPerformed
        // TODO add your handling code here:

        Yöneticiden_öğrenci_ekle y = new Yöneticiden_öğrenci_ekle(yönetici);
        y.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_öğrenci_ekleActionPerformed

    private void btn_ogrenci_güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ogrenci_güncelleActionPerformed
        // TODO add your handling code here:
        Yöneticiden_Öğrenci_güncelleme y = new Yöneticiden_Öğrenci_güncelleme(yönetici);
        y.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_ogrenci_güncelleActionPerformed

    private void btn_guvenli_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guvenli_cikisActionPerformed
        // TODO add your handling code here:
        int soru = JOptionPane.showConfirmDialog(rootPane, "Cikis Yapmak Istediginize Emin misiniz? ", "Dikkat", JOptionPane.YES_NO_CANCEL_OPTION);

        if (soru == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "İyi Günler Dileriz " + yönetici.ad_soyad, "İyi Günler", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        } else if (soru == JOptionPane.NO_OPTION) {

        } else {

        }
    }//GEN-LAST:event_btn_guvenli_cikisActionPerformed

    private void btn_kayitlari_getirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitlari_getirActionPerformed
        // TODO add your handling code here:
        Yönetici_Kayit_Sayfasi y = new Yönetici_Kayit_Sayfasi(yönetici);
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_kayitlari_getirActionPerformed

    private void btn_giris_ekraniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_giris_ekraniActionPerformed
        // TODO add your handling code here:
        Ana_Giris a = new Ana_Giris();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_giris_ekraniActionPerformed

    private void menu_guvenli_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_guvenli_cikisActionPerformed
        // TODO add your handling code here:
        int soru = JOptionPane.showConfirmDialog(rootPane, "Cikis Yapmak Istediginize Emin misiniz? ", "Dikkat", JOptionPane.YES_NO_CANCEL_OPTION);

        if (soru == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "İyi Günler Dileriz " + yönetici.ad_soyad, "İyi Günler", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        } else if (soru == JOptionPane.NO_OPTION) {

        } else {

        }
    }//GEN-LAST:event_menu_guvenli_cikisActionPerformed

    private void menu_giris_ekranina_donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_giris_ekranina_donActionPerformed
        // TODO add your handling code here:

        Ana_Giris a = new Ana_Giris();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_menu_giris_ekranina_donActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Yönetici_Ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Yönetici_Ekrani().setVisible(true);
            }
        });
    }

    public void setlbl_öğrenci(String ism) {
        // label ı düzenler
        lbl_hosgeldiniz_mesaj.setText("Yönetici " + ism + " Hoşgeldiniz ");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris_ekrani;
    private javax.swing.JButton btn_guvenli_cikis;
    private javax.swing.JButton btn_kayitlari_getir;
    private javax.swing.JButton btn_ogrenci_güncelle;
    private javax.swing.JButton btn_öğrenci_ekle;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_hosgeldiniz_mesaj;
    private javax.swing.JMenuItem menu_giris_ekranina_don;
    private javax.swing.JMenuItem menu_guvenli_cikis;
    private javax.swing.JMenu menu_menu;
    // End of variables declaration//GEN-END:variables
}
