/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.burak_erdogan_bp2_proje2;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thebu
 */
public class Öğrenci_bilgileri extends javax.swing.JFrame {

    Kullanici k;

    /**
     * Creates new form Öğrenci_bilgileri
     */
    public Öğrenci_bilgileri(Kullanici kullanici) {
        this.k = kullanici;
        initComponents();
    }

    public Öğrenci_bilgileri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_parola = new javax.swing.JLabel();
        lbl_bölüm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_adsoyad = new javax.swing.JLabel();
        lbl_mail = new javax.swing.JLabel();
        lbl_parola1 = new javax.swing.JLabel();
        lbl_bölüm1 = new javax.swing.JLabel();
        txt_adsoyad = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_parola = new javax.swing.JTextField();
        txt_bölüm = new javax.swing.JTextField();
        btn_geridön = new javax.swing.JButton();
        btn_bilgilerimi_güncelle = new javax.swing.JButton();
        lbl_ogrenci_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();

        lbl_parola.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_parola.setText("Parola :");

        lbl_bölüm.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_bölüm.setText("Bölüm : ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lbl_adsoyad.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_adsoyad.setText("Ad Soyad : ");

        lbl_mail.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_mail.setText("Email : ");

        lbl_parola1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_parola1.setText("Parola :");

        lbl_bölüm1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lbl_bölüm1.setText("Bölüm : ");

        txt_bölüm.setEditable(false);

        btn_geridön.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_geridön.setText("Geri Dön");
        btn_geridön.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geridönActionPerformed(evt);
            }
        });

        btn_bilgilerimi_güncelle.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_bilgilerimi_güncelle.setText("Bilgilerimi Güncelle");
        btn_bilgilerimi_güncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bilgilerimi_güncelleActionPerformed(evt);
            }
        });

        lbl_ogrenci_id.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ogrenci_id.setText("Öğrenci ID : ");

        txt_id.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_adsoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addGap(27, 27, 27)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_geridön, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)
                        .addComponent(btn_bilgilerimi_güncelle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_parola1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_bölüm1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_ogrenci_id, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_bölüm, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txt_id))))
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_adsoyad)
                    .addComponent(txt_adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mail)
                    .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_parola1)
                    .addComponent(txt_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bölüm1)
                    .addComponent(txt_bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ogrenci_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_geridön)
                    .addComponent(btn_bilgilerimi_güncelle))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_geridönActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geridönActionPerformed
        // TODO add your handling code here:

        Ogrenci_ekrani ö = new Ogrenci_ekrani(k);
        ö.setlbl_öğrenci(k.ad_soyad);
        ö.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_geridönActionPerformed

    private void btn_bilgilerimi_güncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bilgilerimi_güncelleActionPerformed
        // TODO add your handling code here:

        Pattern pattern = Pattern.compile("^([a-z]+\\w*){1,}@{1}(stu){1}(.fsm){1}(.edu){1}(.tr){1}$");
        Matcher matcher = pattern.matcher(this.txt_mail.getText());

        if (txt_adsoyad.getText().isEmpty() || txt_mail.getText().isEmpty() || txt_parola.getText().isEmpty()||txt_bölüm.getText().isEmpty()||txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Lütfen Tüm Boşlukları Doldurunuz", "Dikkat", JOptionPane.ERROR_MESSAGE);
        } else {
            if (!matcher.find()) {
                JOptionPane.showMessageDialog(rootPane, "Dikkat Mailinizi Güncellerken Yeni Mailiniz de example@stu.fsm.edu.tr Şeklinde Olmalıdır", "Dikkat", JOptionPane.INFORMATION_MESSAGE);
            } else {
                Kullanici p = new Kullanici();

                p.ad_soyad = this.txt_adsoyad.getText();
                p.mail = txt_mail.getText();
                p.parola = txt_parola.getText();
                p.bölüm = txt_bölüm.getText();
                p.id = Integer.parseInt(txt_id.getText());

                if (db_student_and_manager.kullanıcıGüncelle(p)) {
                    //bilgiler yukarıdaki fonskiyona göre güncellenmektedir
                    JOptionPane.showMessageDialog(rootPane, "Bilgileriniz Başarıyla Güncellenmiştir ", "dikkat", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bilgileriniz Güncellenememiştir", "dikkat", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }


    }//GEN-LAST:event_btn_bilgilerimi_güncelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Öğrenci_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Öğrenci_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Öğrenci_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Öğrenci_bilgileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Öğrenci_bilgileri().setVisible(true);
            }
        });
    }

    public void öğrenci_bilgileri() {

        if (k != null) {

            k = db_student_and_manager.id_e_göre_arama(k.id);
            this.txt_id.setText(k.id + "");
            this.txt_adsoyad.setText(k.ad_soyad);
            this.txt_mail.setText(k.mail);
            this.txt_parola.setText(k.parola);
            this.txt_bölüm.setText(k.bölüm);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bilgilerimi_güncelle;
    private javax.swing.JButton btn_geridön;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_adsoyad;
    private javax.swing.JLabel lbl_bölüm;
    private javax.swing.JLabel lbl_bölüm1;
    private javax.swing.JLabel lbl_mail;
    private javax.swing.JLabel lbl_ogrenci_id;
    private javax.swing.JLabel lbl_parola;
    private javax.swing.JLabel lbl_parola1;
    private javax.swing.JTextField txt_adsoyad;
    private javax.swing.JTextField txt_bölüm;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_parola;
    // End of variables declaration//GEN-END:variables
}
